### ISSUE TITLE
nway matching failure: findTransformECC() takes at most 6 arguments (7 given)

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ophys_nway_matching#32]
findTransformECC() takes at most 6 arguments (7 given)

 /allen/programs/braintv/production/visualbehavior/prod1/specimen_866070199/experiment_container_906963896/OphysNwayCellMatchingStrategy/container_run_1006901430/202002130916_OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE_906963896.log

```
Traceback (most recent call last):
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/site-packages/nway/nway_matching.py", line 413, in <module>
    nmod.run()
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/site-packages/nway/nway_matching.py", line 390, in run
    self.pair_matches[-1].run()
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/site-packages/nway/pairwise_matching.py", line 527, in run
    self.args['CLAHE_clip'])
  File "/allen/aibs/technology/conda/production/ophys_nway_matching/lib/python3.6/site-packages/nway/pairwise_matching.py", line 474, in register_intensity_images
    gaussFiltSize)
TypeError: findTransformECC() takes at most 6 arguments (7 given)
```

**Comment by djkapner** [comment]
@wbwakeman 
`OPHYS_NWAY_CELL_MATCHING_QUEUE` is set to use the conda env:
`/allen/aibs/technology/conda/production/ophys_nway` which is sym-linked to our release deployment:
`/allen/aibs/pipeline/algorithms/conda/envs/ophys_nway/release-21/`

this is fine, as far as I know. Currently, that opencv version is:
opencv-python             4.1.2.30

Meanwhile the queue `OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE` is set to use the conda env:
`/allen/aibs/technology/conda/production/ophys_nway_matching`
That looks to be from December, perhaps when @njmei  was trying to fix my deployment issues. That conda env has:
opencv-python             3.4.5.20
which differs in how many arguments `findTransformECC` takes.

We should make sure both queues are using the correct conda env:
`/allen/aibs/technology/conda/production/ophys_nway`

**Comment by wbwakeman** [comment]
@djkapner Thanks for seeing that.  I will change it and try those again

**Comment by wbwakeman** [comment]
That fixed it.  Glad it was an easy one!
