### ISSUE TITLE
KeyError with quick start usage

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/ophys_nway_matching#72]
Running the quick start usage from the command line yields an error. Here is the error traceback. I can't seem to find where `args["output_directory"]` ought to be assigned to fix it.

```python
PS C:\Users\carter.peene\Desktop\Projects\cell_matching> python ophys_nway_matching/src/nway/nway_matching.py --input_json save_json_containers2/input_0.json --output_json ./carter_output.json
WARNING:root:many=True not supported from argparse
INFO:NwayMatching:NWAY_COMMIT_SHA None
INFO:NwayMatching:Nway matching version 0.6.0
Traceback (most recent call last):
  File "C:\Users\carter.peene\Desktop\Projects\cell_matching\ophys_nway_matching\src\nway\nway_matching.py", line 502, in <module>
    nmod.run()
  File "C:\Users\carter.peene\Desktop\Projects\cell_matching\ophys_nway_matching\src\nway\nway_matching.py", line 435, in run
    self.make_masks_from_dicts()
  File "C:\Users\carter.peene\Desktop\Projects\cell_matching\ophys_nway_matching\src\nway\nway_matching.py", line 183, in make_masks_from_dicts
    self.args['output_directory']))
KeyError: 'output_directory'
PS C:\Users\carter.peene\Desktop\Projects\cell_matching>
```

**Comment by rcpeene** [comment]
Seems like the quick start usage might need to include the specification of the `--output_directory` argument.
